### ISSUE TITLE
请问win下是不是无法使用呢？

### ISSUE THREAD

**Issue by zasl** [ziwenxie/netease-dl#14]
我是win10，python 3.6，运行pip3 install netease-dl 提示错误

Command "d:\users\xxx\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='D:\\Users\\xxx\\AppData\\Local\\Temp\\pip-build-k416jnir\\pycrypto\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record D:\Users\uslxt\AppData\Local\Temp\pip-3ady5wu1-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in D:\Users\xxx\AppData\Local\Temp\pip-build-k416jnir\pycrypto\

很想用这个下载音乐啊。

**Comment by ziwenxie** [comment]
https://github.com/ziwenxie/netease-dl/issues/11 => 现在pycrypto在windows下有兼容性问题

**Comment by ziwenxie** [comment]
fixed => https://github.com/ziwenxie/netease-dl/pull/16
