### ISSUE TITLE
pycrypto is dead, use "pycryptodome  instead

### ISSUE THREAD

**Issue by 0017031** [ziwenxie/netease-dl#25]
https://github.com/dlitz/pycrypto/issues/238

tl;dr: PyCrypto is dead. Switch to PyCryptodome (GitHub: https://github.com/Legrandin/pycryptodome PyPi: https://pypi.python.org/pypi/pycryptodome). 

As you may or may not have noticed the last change to PyCrypto was made three years ago.
--

**Comment by mengmo** [comment]
https://github.com/ziwenxie/netease-dl/issues/11
https://github.com/ziwenxie/netease-dl/commit/ba6ddee34c976dee7c67b0078d6a687888469ee5

**Comment by 0017031** [comment]
thank you for the reminder @mengmo
