### ISSUE TITLE
功能建议：断点下载

### ISSUE THREAD

**Issue by leopku** [ziwenxie/netease-dl#3]
因为有歌名含有特殊字符，下载过程已经断两次。
而下载都是要从第一首歌起
能否考虑加个功能，从上次断开的地方继续下载，之前下载过的就不要重要下载了。

**Comment by ziwenxie** [comment]
已经修复，请更新到最新的版本，之前下载过的歌曲将不会重新下载了。

**Comment by leopku** [comment]
赞！
