### ISSUE TITLE
请问如何指定下载的品质(比如320kbps)？

### ISSUE THREAD

**Issue by withlqs** [ziwenxie/netease-dl#4]

**Comment by ziwenxie** [comment]
[默认自动下载320k的歌曲](https://github.com/ziwenxie/netease-dl/blob/master/netease/weapi.py#LC297)，但是可能会出现有的歌曲并没有320k版本只有128k版本，比如周杰伦的歌曲。

**Comment by withlqs** [comment]
明白了，谢谢！
